MDScreen:

    MDLabel:
        text: "VICI"
        halign: "center"
        pos_hint: {"center_x": 0.5, "center_y": 0.88}
        font_style: "H3"

    MDLabel:
        text: "Press Connect to connect device!"
        halign: "center"
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
        font_size: "16sp"

    MDFillRoundFlatButton:
        text: "Connect"
        pos_hint: {"center_x": 0.5, "center_y": 0.12}
        font_style: "Button"
        font_size: "24sp"
